extends:
  - eslint:recommended
  - plugin:import/errors
  - plugin:import/warnings
  - plugin:prettier/recommended
  - prettier

parserOptions:
  sourceType: module
  ecmaVersion: 2020

settings:
  import/resolver: 
    node: 
      extensions: ['.js', '.jsx']

env: 
  es6: true

rules:
  no-console: ['warn', { allow: ['clear', 'info', 'error', 'dir', 'trace', 'debug'] }]
  no-unused-vars: ['error', { ignoreRestSiblings: true }]
