processors: stylelint-processor-styled-components

extends: 
  - stylelint-config-standard
  - stylelint-config-styled-components

rules: 
  shorthand-property-no-redundant-values: true
  declaration-no-important: true