processors: stylelint-processor-styled-components

extends: 
  - stylelint-config-standard
  - stylelint-config-styled-components

rules: 
  number-leading-zero: never
  shorthand-property-no-redundant-values: true
