name: foodcarboncalculator CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '15.x'
    - name: Install Dependencies
      run: yarn --frozen-lockfile
    - name: frontend:lint
      run: yarn workspace @foodcarboncalculator/frontend lint 
    - name: frontend:test
      run: yarn workspace @foodcarboncalculator/frontend test 